# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formdemografi', '0003_auto_20170629_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanname',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='humanname',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='humanname',
            name='id_pengguna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pengguna_humanname_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='humanname',
            name='status_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humanname',
            name='status_sinkronisasi',
            field=models.BooleanField(default=False),
        ),
    ]
