# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdemografi', '0005_auto_20170629_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabel_sinkronisasi_client',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
