# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdemografi', '0008_auto_20170630_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanname',
            name='family',
            field=models.CharField(blank=True, help_text='Nama keluarga', max_length=50),
        ),
    ]
